version: '1'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - mynetwork

        
  # backend:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"


networks:
  mynetwork:
    driver: bridge
